config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),            #127.0.0.1:8000/
    path('pybo/', include('pybo.urls')),   #127.0.0.1:8000/pybo/
    path('common/', include('common.urls')),#127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.poll_list, name="poll_list"),
    path('<int:question_id>/', views.poll_detail, name="poll_detail"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('<int:question_id>/result/', views.result, name="result"),
]

poll/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from poll.models import Question, Choice

# 설문 목록
def poll_list(request):
    question_list = Question.objects.all()
    context = {'question_list': question_list}
    return render(request, 'poll/poll_list.html', context)

# 설문 상세
def poll_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'poll/poll_detail.html', context)

# 투표하기
def vote(request, question_id):
    try:
        question = get_object_or_404(Question, pk=question_id)
        choice = request.POST['choice']  # name에서 가져오기
        sel_choice = question.choice_set.get(id=choice)
    except KeyError:
        return render(request, 'poll/poll_detail.html', {
            'question': question,
            'error_message': '항목을 선택 해주세요'
        })
    else:
        sel_choice.votes += 1
        sel_choice.save()
        return HttpResponseRedirect(reverse('poll:result', args=(question.id,)))

# 투표 결과
def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'poll/result.html', context)

templates/poll/poll_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-6">
            <form action="{% url 'poll:vote' question.id %}" method="post" >
                {% csrf_token %}
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-title" style="font-size: 1.3rem">{{ question.question_text }}</div>
                        <div class="card-text my-3">
                            {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                            {% endif %}

                            {% for choice in question.choice_set.all  %}
                            <div class="form-group px-2">
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                                                    value="{{ choice.id }}">
                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                            </div>
                            {% endfor %}
                            <input type="submit" value="투표" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/poll/poll_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-12">
            <h4>설문 목록</h4>
        </div>
        {% if question_list %}
            {% for question in question_list %}
            <div class="col-4 my-3">
                <div class="card" style="height: 12rem">
                    <div class="card-body">
                        <div class="card-text my-2" style="line-height: 2rem">
                            {{ question.question_text }}
                        </div>
                        <a href="{% url 'poll:poll_detail' question.id %}"
                           class="btn btn-primary my-4">투표하기 &raquo;</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>설문이 없습니다.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/poll/result.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-6">
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-title" style="font-size: 1.3rem">투표 결과</div>
                    <div class="card-text" style="line-height: 3rem">
                        <ul>
                            {% for choice in question.choice_set.all  %}
                            <li>
                                {{ choice.choice_text }} -- {{ choice.votes }} votes
                            </li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'poll:poll_detail' question.id %}" class="btn btn-info">다시 투표하시겠습니까?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}