config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),            #127.0.0.1:8000/
    path('pybo/', include('pybo.urls')),   #127.0.0.1:8000/pybo/
    path('common/', include('common.urls')),#127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.poll_list, name="poll_list"),
    path('<int:question_id>/', views.poll_detail, name="poll_detail"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('<int:question_id>/result/', views.result, name="result"),
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'pybo'

urlpatterns = [
    #base_views
    #127.0.0.1:8000/pybo/
    path('', base_views.index, name='index'),
    #127.0.0.1:8000/pybo/board/
    path('board/', base_views.board, name='board'),
    #127.0.0.1:8000/pybo/1/
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views
    #127.0.0.1:8000/pybo/question/create/ 질문 등록
    path('question/create/', question_views.question_create, name="question_create"),
    #질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # answer_views
    # 답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),

    # vote_views
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),

    # comment_views
    # 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
          name='comment_create_question'),
]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models
# Question, Answer 모델 생성

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from .models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:    #중첩 클래스(내부 클래스)
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '질문 내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content': '답변 내용'}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content': '댓글 내용'}

pybo/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

def index(request):
    return render(request, 'pybo/index.html')

# 전체 목록 조회
def board(request):
    #페이지 - #127.0.0.1:8000/pybo/?page=1
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date') #내림차순 정렬
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  #제목 검색
            Q(content__icontains=kw) |  #질문내용 검색
            Q(answer__content__icontains=kw) |  # 답변내용 검색
            Q(author__username__icontains=kw) |  #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  #답변 글쓴이
        ).distinct()   # 중복 제거한 유일한 내용

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw} #page, kw 추가
    return render(request, 'pybo/question_list.html', context)

# 상세 페이지 조회
def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    cotext = {'question': question}
    return render(request, 'pybo/detail.html', cotext)

# 질문 등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장
            question.author = request.user  # 세션 권한이 있는 user(author)
            question.create_date = timezone.now() # 등록일
            question.save()  # 실제 저장
            return redirect('pybo:board')
    else:  # request.method == 'GET':
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

# 답변 등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    #question = Question.objects.get(id=question_id)  #질문 1개 가져오기
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question  # 질문을 답변에 저장(외래키)
            form.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'form': form}
    return render(request, 'pybo:detail', context)

#질문 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user   #세션권한이 있는 user 생성
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)  #기존의 내용을 가져옴(question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = Question.objects.get(id=question_id)
    question.delete()
    return redirect('pybo:index')

pybo/views/answer_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

# 답변 등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    #question = Question.objects.get(id=question_id)  #질문 1개 가져오기
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question  # 질문을 답변에 저장(외래키)
            form.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'form': form}
    return render(request, 'pybo:detail', context)

pybo/views/base_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

def index(request):
    return render(request, 'pybo/index.html')

# 전체 목록 조회
def board(request):
    #페이지 - #127.0.0.1:8000/pybo/?page=1
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date') #내림차순 정렬
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  #제목 검색
            Q(content__icontains=kw) |  #질문내용 검색
            Q(answer__content__icontains=kw) |  # 답변내용 검색
            Q(author__username__icontains=kw) |  #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  #답변 글쓴이
        ).distinct()   # 중복 제거한 유일한 내용

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw} #page, kw 추가
    return render(request, 'pybo/question_list.html', context)

# 상세 페이지 조회
def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    cotext = {'question': question}
    return render(request, 'pybo/detail.html', cotext)

pybo/views/comment_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm, CommentForm

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) #가저장
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save() #저장 완료
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

pybo/views/question_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

# 질문 등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장
            question.author = request.user  # 세션 권한이 있는 user(author)
            question.create_date = timezone.now() # 등록일
            question.save()  # 실제 저장
            return redirect('pybo:board')
    else:  # request.method == 'GET':
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#질문 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user   #세션권한이 있는 user 생성
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)  #기존의 내용을 가져옴(question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = Question.objects.get(id=question_id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

@login_required(login_url='common:login')
def vote_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)  # 추천 추가(1증가)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="content">댓글 내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/pybo/detail.html
{% extends 'base.html' %}
<!--base.html과 연결(상속, 확장)-->
{% block content %}
  <div class="container my-3">
    <!-- 추천 오류 표시 -->
      {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul>
                <li>{{ message.message }}</li>
            </ul>
            {% endfor %}
        </div>
      {% endif %}
    <!--질문 내용-->
      <h2 class="border-bottom py-2">{{ question.subject }}</h2>
      <!-- 추천 영역 -->
      <div class="row my-3">
          <div class="col-1">
              <div class="bg-light text-center p-3 font-weight-bolder mb-1">
                  {{ question.voter.count }}
              </div>
              <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
                 class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
          </div>
          <div class="col-11">
              <div class="card my-3"> <!--기존 내용-->
                  <div class="card-body">
                      <div class="card-text" style="white-space: pre-line;">
                          {{ question.content }}
                      </div>
                      <div class="d-flex justify-content-end">
                          <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                          </div>
                          <div class="badge badge-light p-2 text-left">
                              <div class="mb-2">{{ question.author.username }}</div>
                              <div>{{ question.create_date }}</div>
                          </div>
                      </div>
                      {% if request.user == question.author %}
                      <div class="my-3">
                          <a href="{% url 'pybo:question_modify' question.id %}"
                             class="btn btn-sm btn-outline-secondary">수정</a>
                          <a data-uri="{% url 'pybo:question_delete' question.id %}" href="#"
                             class="delete btn btn-sm btn-outline-secondary">삭제</a>
                      </div>
                      {% endif %}
                      <!--질문 댓글 Start -->
                      {% if question.comment_set.count > 0 %}
                      <div class="mt-3">
                          {% for comment in question.comment_set.all %}
                              <div class="comment py-2 text-muted">
                                  <span style="white-space: pre-line">{{ comment.content }}</span>
                              </div>
                          {% endfor %}
                      </div>
                      {% endif %}
                      <div>
                          <a href="{% url 'pybo:comment_create_question' question.id %}"><small>댓글 추가...</small></a>
                      </div>
                  </div><!-- card-body -->
              </div> <!--card 끝-->
          </div>

    </div>

      <h5 class="border-bottom my-3 py-2">
          {{ question.answer_set.count }}개의 답변이 있습니다.
      </h5>
      <!--답변 내용-->
      {% for answer in question.answer_set.all %}
      <div class="card my-3">
          <div class="card-body">
              <div class="card-text" style="white-space: pre-line;">
                  {{ answer.content }}
              </div>
              <div class="d-flex justify-content-end">
                  <div class="badge badge-light p-2 text-left">
                      <div class="mb-2">{{ answer.author.username }}</div>
                      <div>{{ answer.create_date }}</div>
                  </div>
              </div>
          </div>
      </div>
      {% endfor %}
      <!-- 답변 폼 -->
      <form action="{% url 'pybo:answer_create' question.id %} " method="post" class="my-3">
          {% csrf_token %}
          <div class="form-group">
              <textarea name="content" id="content" rows="10" class="form-control"
                        {% if not user.is_authenticated %}disabled {% endif %}></textarea>
          </div>
          <input type="submit" value="답변 등록" class="btn btn-primary">
      </form>
  </div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function(){
    //삭제 시
    $('.delete').on('click', function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = $(this).data('uri');  //data-uri 경로 설정
        }
    });

    //추천 시
    $('.recommend').on('click', function(){
        if(confirm("정말로 추천하시겠습니까?")){
            location.href = $(this).data('uri');
        }
    })
  });
</script>
{% endblock %}

templates/pybo/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="container">
    <div class="jumbotron">
        <div class="text-center"><h2>Welcome~ Have a nice Day!</h2></div>
    </div>
    <div class="text-center">
        <img src="{% static 'pybo/images/coffee-blue.jpg' %}" id="pic">
    </div>
    <div>
        <p id="demo" class="text-center my-3"></p>
    </div>

</div>
{% endblock %}
{% block script %}
<script>
    //메인 이미지 이벤트
   var pic = document.getElementById('pic')
   pic.addEventListener('mouseover', function(){
       pic.src = '../../static/pybo/images/coffee-pink.jpg';
   });

   pic.addEventListener('mouseout', function(){
       pic.src = '../../static/pybo/images/coffee-blue.jpg';
   });

   //디지털 시계
   setInterval(myWatch, 1000)
   function myWatch(){
     var date = new Date();
     var now = date.toLocaleTimeString();
     document.getElementById('demo').innerHTML = now;
   }

</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
<!--base.html과 연결(상속, 확장)-->
{% block content %}
<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류 표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <!-- 검색창 -->
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw"
                   value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary"
                        type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <!-- 게시글 목록 -->
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style="width: 55%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list  %}
            {% for question in question_list %}
            <tr>
                <!-- 전체게시물수 - 시작인덱스 - 현재인덱스 + 1 -->
                <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{ question.subject }}
                    </a>
                </td>
                <td>
                    {% if question.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">
                        {{ question.voter.all.count }}
                    </span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
    <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="#"
                data-page="{{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#" >
                이전
            </a>
        </li>
        {% endif %}

    <!-- 현재 페이지 -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#" data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="#" data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endfor %}
    <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="#"
               data-page="{{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#" >
                다음
            </a>
        </li>
        {% endif %}
    </ul>

    <!-- 페이징 처리 끝-->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록</a>
</div>
<!-- 검색 폼 -->
<form id="searchForm" method="get" action="{% url 'pybo:board' %}">
    <input type="hidden" name="kw" id="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" name="page" id="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //페이지 번호 클릭
        $(".page-link").on('click', function(){
            $('#page').val($(this).data('page')); //data-page의 page번호를 id가 page인 필드에 설정
            $('#searchForm').submit();  //폼을 전송
        });

        //검색 버튼 클릭
        $("#btn_search").on('click', function(){
            $("#kw").val($('.kw').val()); //입력된 kw값을 id가 kw인 필드에 설정
            $('#page').val(1);            //1페이지부터 검색
            $('#searchForm').submit();  //폼을 전송
        });
    });
</script>

{% endblock %}