common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    #127.0.0.1:8000/common/login/
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index),            #127.0.0.1:8000/
    path('pybo/', include('pybo.urls')),   #127.0.0.1:8000/pybo/
    path('common/', include('common.urls')),#127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.poll_list, name="poll_list"),
    path('<int:question_id>/', views.poll_detail, name="poll_detail"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('<int:question_id>/result/', views.result, name="result"),
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'pybo'

urlpatterns = [
    #base_views
    #127.0.0.1:8000/pybo/
    path('', base_views.index, name='index'),
    #127.0.0.1:8000/pybo/board/
    path('board/', base_views.board, name='board'),
    #127.0.0.1:8000/pybo/1/
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views
    #127.0.0.1:8000/pybo/question/create/ 질문 등록
    path('question/create/', question_views.question_create, name="question_create"),
    #질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #질문 삭제
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # answer_views
    # 답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),

    # vote_views
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),

    # comment_views
    # 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
          name='comment_create_question'),
]

pybo/views/base_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

def index(request):
    return render(request, 'pybo/index.html')

# 전체 목록 조회
def board(request):
    #페이지 - #127.0.0.1:8000/pybo/?page=1
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    #조회
    question_list = Question.objects.order_by('-create_date') #내림차순 정렬
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  #제목 검색
            Q(content__icontains=kw) |  #질문내용 검색
            Q(answer__content__icontains=kw) |  # 답변내용 검색
            Q(author__username__icontains=kw) |  #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  #답변 글쓴이
        ).distinct()   # 중복 제거한 유일한 내용

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw} #page, kw 추가
    return render(request, 'pybo/question_list.html', context)

# 상세 페이지 조회
def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    cotext = {'question': question}
    return render(request, 'pybo/detail.html', cotext)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Hello~ PyWeb!</title>
    <link rel="stylesheet" href="{% static 'pybo/css/bootstrap.css' %}">
    <!--<link rel="stylesheet" href="{% static 'pybo/css/style.css' %}">-->
</head>
<body>
<!--네비게이션 바-->
{% include 'navbar.html' %}
<!--기본 템플릿 안에 삽입될 내용 start-->
{% block content %}

{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 End-->
<!-- 햄버거 메뉴 -->
<script src="{% static 'pybo/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'pybo/js/bootstrap.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}

{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 오류 처리 -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류 출력 -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field.errors %} <!-- 넌필드 오류 출력  -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pyweb</a>
    <!--햄버거 버튼-->
    <button class="navbar-toggler ml-auto" type="button"  data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!--로그인 메뉴-->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %} <!-- 로그인 되었다면 -->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pybo:board' %}">질문/답변</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'poll:poll_list' %}">설문조사</a>
            </li>
        </ul>
    </div>
</nav>